In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split  #scikit-learn
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
import pickle
from tensorflow.keras.models import load_model
from konlpy.tag import Kkma, Okt

In [3]:
pd.set_option('display.unicode.east_asian_width', True)
pd.set_option('display.max_columns', 20)
df = pd.read_csv('output/music_data_coulmns.csv')
print(df.head())
df.info()

                      title              artist genre  \
0         horizon                      박현광    댄스   
1    Starry Night             NATURE  네이처     댄스   
2         우리                   수인  Swuin     댄스   
3     겨울 헌팅송                 my  삼마이     댄스   
4        BIG LiPS                      양준일    댄스   

                                                                                 lyric  \
0  날고 싶던 그날에 날 수 없단 걸 알았어 구름을 가르며 나는 새를 부러워만 했었어 ...     
1  Oh starry night 우릴 위한 이 밤 별빛은 너를 더 빛나게 해 Oh st...                     
2  Long time no see 다들 잘 지내 반가워 사실은 우리 그렇게 친한 사이는...                
3  드디어 찾아온 겨울 우리들의 스키장 저기좀 봐 그녀를 봐 여름 바닷가에서 봤어나 나...   
4  What 봐라 왔냐 니 bye 완전 반응이 big 와 봐라 반응이 bye Gathe...                     

                                                            All_Columns  
0    horizon          : 박현광  :날고 싶던 그날에 날 수 없단 걸 ...      
1    Starry Night          : NATURE  네이처   :Oh st...                  
2    우리             : 수인  Swuin   :Long time no s...          

In [19]:
X = df.All_Columns
Y = df.genre


In [22]:
X

0       [horizon, :, 박현, 광, :, 날, 고, 싶다, 그날, 에, 날, 수, ...
1       [Starry, Night, :, NATURE, 네이처, :, Oh, starry,...     
2       [우리, :, 수인, Swuin, :, Long, time, no, see, 다, ...   
3       [겨울, 헌팅, 송, :, my, 삼, 마이, :, 드디어, 찾아오다, 겨울, 우리...
4       [BIG, LiPS, :, 양준, 일, :, What, 보다, 오다, 니, bye,...
                                  ...                            
6334      바람아 말해 줄래          : 굿맨  Goodman   :흘러 가는 저 ...
6335      대낮에 한 이별          : 선예  span    span 임슬옹  :마...
6336      내 생각을 들려주지 않을 거예요  with 이예린           : 겸  G...
6337      중독          : 남궁진영  :밤이 되면 올까 자꾸 널 찾아 아마 너에게...
6338      다시 오지 않을 그 밤          : 안솔희 블루베리   :오늘밤도 내 곁...
Name: All_Columns, Length: 6339, dtype: object

In [5]:
with open('./output/encoder.pickle', 'rb') as f:
    encoder = pickle.load(f)
labeled_Y = encoder.transform(Y)
print(labeled_Y)
print(encoder.classes_)
print(labeled_Y[:5])
print(encoder)


[1 1 1 ... 4 4 4]
['R amp B Soul' '댄스' '랩 힙합' '록 메탈' '발라드' '발라드  록 메탈' '성인가요 트로트' '포크 블루스']
[1 1 1 1 1]
LabelEncoder()


In [6]:
labeled_Y = encoder.transform(X)
print(encoder.classes_)
print(labeled_Y[:5])

ValueError: y contains previously unseen labels: '  horizon          : 박현광  :날고 싶던 그날에 날 수 없단 걸 알았어 구름을 가르며 나는 새를 부러워만 했었어 태양 아래는 더 뜨겁다며 겁을 또 먹었어 저 작은 날개로 빠르게 나는 걸 바라만 보던 나인걸 있잖아 모든 건 내가 만드는 것 눈 감고 뛰어봐 구름 위로 날아 저 끝까지 날아 바람을 가르는 내 모습 느껴봐 두렵지 않은걸 수평선 가까이 다가간 것 같아 내가 날고 싶었던 그날에 날 수 있었어 내 맘은 그저 평범한 날 그런 날에 평범하긴 싫었어 날 비웃던 그런 시선들도 웃어넘겼어 다 이 작은 날개로 빠르게 나는 걸 보여주고 싶었던 날 있잖아 모든 건 내가 만드는 것 눈 뜨고 나를 봐 구름 위로 날아 저 끝까지 날아 바람을 가르는 내 모습 느껴봐 두렵지 않은걸 수평선 가까이 다가간 것 같아 내가 어렸을 적 작은 내 꿈을 아직까지 숨겨왔어 별거 아닌 줄 알았어 지금도 그땐 작다고만 생각했던 내 안에 이 맘 내가 커가듯 이 꿈도 점점 더 커져가 바람을 가르는 내 모습 느껴봐 두렵지 않은걸 수평선 가까이 다가간 것 같아 내가 하늘에서 보는 바다를 넌 알까 이렇게 멋진걸 내가 본 바다는 하늘과 같단 걸 알까 \n'

In [7]:
onehot_Y = to_categorical(labeled_Y)
print(onehot_Y)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [23]:
okt = Okt()
for i in range(len(X)):
    X[i] = okt.morphs(X[i], stem=True)

stopwords = pd.read_csv('./data2/stopwords.csv',index_col=0)
stopwords

for j in range(len(X)):
    words = []
    for i in range(len(X[j])):
        if len(X[j][i]) > 1:
            if X[j][i] not in list(stopwords['stopword']):
                words.append(X[j][i])
    X[j] = ' '.join(words)
print(X[1])

AssertionError: phrase input should be string, not <class 'list'>

In [ ]:
with open('./output/music_melon_token (1).pickle', 'rb') as f:
    token = pickle.load(f)
tokened_X = token.texts_to_sequences(X)

In [ ]:
for i in range(len(tokened_X)):
    if len(tokened_X[i]) > 1030:
        tokened_X[i] = tokened_X[i][:1030]
X_pad = pad_sequences(tokened_X, 1030)
label = encoder.classes_
model = load_model('./output/music_classfication_model_0.43542855978012085.h5')
preds = model.predict(X_pad)
predicts = []
for pred in preds:
    predicts.append(label[np.argmax(pred)])

In [ ]:
df['predict'] = predicts
df['OX'] = 0
for i in range(len(df)):
    if df.loc[i, 'genre'] == df.loc[i, 'predict']:
        df.loc[i, 'OX'] = 'O'
    else:
        df.loc[i, 'OX'] = 'X'

print(df['OX'].value_counts()/len(df))
for i in range(len(df)):
    if df['genre'][i] != df['predict'][i]:
        print(df.iloc[i])

In [ ]:
print(df.title[0])
print(df.iloc[0])
print(preds[0][np.argmax(preds[0])])
print(label[np.argmax(preds[0])])