In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split  #scikit-learn
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
import pickle
from konlpy.tag import Kkma, Okt

In [11]:
df = pd.read_csv('./output/music_data_coulmns (1).csv')
pd.set_option('display.unicode.east_asian_width',True)
df.reset_index(drop=False ,inplace=True)
# df= df[['index','title','artist','genre','lyric']]
df.set_index('index',inplace=True)
df
# df["all"] = df[["title","artist","lyric"]]
# df
X = df.All_Columns
Y = df.genre
df.info()
X


<class 'pandas.core.frame.DataFrame'>
Int64Index: 6339 entries, 0 to 6338
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   title        6339 non-null   object
 1   artist       6339 non-null   object
 2   genre        6339 non-null   object
 3   lyric        6339 non-null   object
 4   All_Columns  6339 non-null   object
dtypes: object(5)
memory usage: 297.1+ KB


index
0         horizon          : 박현광  :날고 싶던 그날에 날 수 없단 걸 ...
1         Starry Night          : NATURE  네이처   :Oh st...      
2         우리             : 수인  Swuin   :Long time no s...     
3         겨울 헌팅송          :  my  삼마이   :드디어 찾아온 겨울 우리들...
4         BIG LiPS          : 양준일  :What 봐라 왔냐 니 bye 완...
                                   ...                            
6334      바람아 말해 줄래          : 굿맨  Goodman   :흘러 가는 저 ...
6335      대낮에 한 이별          : 선예  span    span 임슬옹  :마...
6336      내 생각을 들려주지 않을 거예요  with 이예린           : 겸  G...
6337      중독          : 남궁진영  :밤이 되면 올까 자꾸 널 찾아 아마 너에게...
6338      다시 오지 않을 그 밤          : 안솔희 블루베리   :오늘밤도 내 곁...
Name: All_Columns, Length: 6339, dtype: object

In [18]:
from tensorflow.python.keras.utils.np_utils import to_categorical
encoder = LabelEncoder()
Label_Y = encoder.fit_transform(Y)
print(encoder.classes_)
print(Label_Y[:5])
with open('./output/encoder.pickle','wb') as f:
    pickle.dump(encoder, f)
onehot_Y = to_categorical(Label_Y)
print(onehot_Y)

['R amp B Soul' '댄스' '랩 힙합' '록 메탈' '발라드' '발라드  록 메탈' '성인가요 트로트' '포크 블루스']
[1 1 1 1 1]
[[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
okt = Okt()
for i in range(len(X)):
    X[i] = okt.morphs(X[i], stem=True)

In [47]:
stopwords = pd.read_csv('./data2/stopwords.csv' ,index_col=0)

for j in range(len(X)):
    words = []
    for i in range(len(X[j])):
        if len(X[j][i]) > 1:
            if X[j][i] not in list(stopwords['stopword']):
                words.append(X[j][i])
    X[j] = ' '.join(words)
print(X[1])

Oh starry night 우릴 별빛 빛나다 Oh starry night 우릴 별빛 빛나다 오늘 따르다 떠나다 싶다 바람 따르다 걷다 싶다 갈다 멀리 It alright 이대로 좋다 순간 멈추다 대도 좋다 에게만 느껴지다 떨리다 싫다 가까이 오다 Oh starry night 우릴 별빛 빛나다 Oh starry night 든지 좋다 발걸음 닿다 도시 벗어나다 싶다 에게만 싶다 비밀 궁금하다 잡다 Oh starry night 우릴 별빛 빛나다 Oh starry night 든지 좋다 발걸음 닿다 손끝 닿다 귓가 들리다 심장소리 꿈속 헤매다 기분 완벽하다 하루 잖다 Oh starry night 우릴 별빛 빛나다 Oh starry night 든지 좋다 발걸음 닿다 Oh starry night 우릴 별빛 빛나다 Oh starry night 든지 좋다 떠나다


In [15]:
token = Tokenizer()
token.fit_on_texts(X)
tokened_X = token.texts_to_sequences(X)
print(tokened_X[0])
with open('./output/music_token.pickle', 'wb') as f:
    pickle.dump(token, f)
wordsize = len(token.word_index) + 1
print(wordsize)
print(token.word_index)

[7460, 12, 12360, 7461, 12, 25, 109, 54, 400, 4, 25, 37, 19, 88, 106, 428, 3, 3370, 11, 15, 431, 17, 2292, 2, 811, 512, 15, 35, 419, 918, 3, 69, 279, 128, 295, 1258, 49, 924, 11, 15, 88, 346, 16, 11, 1029, 13, 114, 175, 6, 8, 283, 41, 75, 1076, 535, 16, 428, 311, 25, 71, 128, 160, 147, 25, 71, 159, 3, 3370, 6, 156, 304, 16, 498, 30, 2069, 815, 668, 41, 43, 6, 8, 25, 109, 54, 400, 4, 25, 37, 13, 6, 76, 14, 321, 1332, 25, 68, 25, 4, 1332, 310, 25, 2218, 68, 848, 26, 18, 155, 1361, 39, 1, 295, 1258, 49, 924, 11, 15, 88, 601, 54, 25, 13, 114, 175, 6, 8, 283, 41, 75, 289, 73, 16, 428, 311, 25, 71, 128, 160, 147, 25, 71, 159, 3, 3370, 6, 156, 304, 16, 498, 30, 2069, 815, 668, 41, 43, 6, 8, 436, 401, 295, 6, 107, 3, 209, 147, 875, 60, 1741, 98, 206, 106, 96, 18, 947, 295, 87, 2, 6, 79, 4, 1, 76, 6, 8, 573, 1, 107, 18, 448, 35, 830, 159, 3, 3370, 6, 156, 304, 16, 498, 30, 2069, 815, 668, 41, 43, 6, 8, 162, 90, 16, 362, 17, 83, 106, 204, 713, 88, 6, 8, 16, 362, 15, 162, 141, 43, 88, 106]
33105


In [16]:
max = 0
for i in range(len(tokened_X)):
    if max < len(tokened_X[i]):
        max = len(tokened_X[i])
print(max)

942


In [17]:
X_pad = pad_sequences(tokened_X, max)
print(X_pad[:10])

X_train, X_test, Y_train, Y_test = train_test_split(
    X_pad, onehot_Y, test_size=0.1)
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

xy = X_train, X_test, Y_train, Y_test
np.save(
    './output/music_data_max_{}_wordsize_{}'.format(max, wordsize), xy)

[[    0     0     0 ...    43    88   106]
 [    0     0     0 ...   151    37    13]
 [    0     0     0 ...    10    10    10]
 ...
 [    0     0     0 ...  3576   126 12372]
 [    0     0     0 ...    21    50   100]
 [    0     0     0 ...  1151   299  3826]]
(5705, 942) (5705, 8)
(634, 942) (634, 8)


C:\Anaconda\envs\music_category_classification\lib\site-packages\numpy\lib\npyio.py:528: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)
